// <auto-generated />
using System;
using GestionBeneficios.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionBeneficios.Infrastructure.Migrations
{
    [DbContext(typeof(BeneficiosDbContext))]
    partial class BeneficiosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciclo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoAlumno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmAlumnoCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Denominacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailPersonal")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaSyncUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AlumnoId");

                    b.HasIndex("CodigoAlumno")
                        .IsUnique();

                    b.HasIndex("CrmAlumnoCodigo");

                    b.HasIndex("Dni");

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.AuditoriaEvento", b =>
                {
                    b.Property<long>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntidadId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("Entidad", "FechaUtc");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Beneficio", b =>
                {
                    b.Property<int>("BeneficioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostoPuntos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficioId");

                    b.ToTable("Beneficio", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Canje", b =>
                {
                    b.Property<int>("CanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CanjeId"));

                    b.Property<int>("BeneficioId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaProcesoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitudUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("PuntosUsados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SolicitadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanjeId");

                    b.HasIndex("BeneficioId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Canje", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.CargaMasiva", b =>
                {
                    b.Property<int>("CargaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargaId"));

                    b.Property<DateTime?>("CompletadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("FilasInvalidas")
                        .HasColumnType("int");

                    b.Property<int>("FilasProcesadas")
                        .HasColumnType("int");

                    b.Property<int>("FilasValidas")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalFilas")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargaId");

                    b.ToTable("CargaMasiva", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.CargaMasivaDetalle", b =>
                {
                    b.Property<long>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetalleId"));

                    b.Property<int>("CargaId")
                        .HasColumnType("int");

                    b.Property<string>("Errores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsValido")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroFila")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Procesado")
                        .HasColumnType("bit");

                    b.HasKey("DetalleId");

                    b.HasIndex("CargaId");

                    b.ToTable("CargaMasivaDetalle", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfiguracionId");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ConfiguracionSistema", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Contratacion", b =>
                {
                    b.Property<int>("ContratacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContratacionId"));

                    b.Property<DateTime?>("ActualizadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("MesContratacion")
                        .HasColumnType("int");

                    b.Property<string>("PerfilSolicitado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PuntosGenerados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SectoristaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sueldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContratacionId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.HasIndex("SectoristaId");

                    b.HasIndex("AlumnoId", "FechaInicio");

                    b.HasIndex("EmpresaId", "FechaInicio");

                    b.ToTable("Contratacion", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.CorreoEnviado", b =>
                {
                    b.Property<long>("CorreoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CorreoId"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CuerpoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnviadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<int?>("PlantillaId")
                        .HasColumnType("int");

                    b.HasKey("CorreoId");

                    b.HasIndex("Estado");

                    b.ToTable("CorreoEnviado", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.EmpresaAsociada", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CrmCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmEmpresaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EjecutivoComercial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoCrm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FechaAltaCrm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gerencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaginaWeb")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Promotor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UltimaSyncUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("EmpresaId");

                    b.HasIndex("CrmEmpresaId")
                        .IsUnique();

                    b.HasIndex("RazonSocial");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("EmpresaAsociada", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.PlantillaCorreo", b =>
                {
                    b.Property<int>("PlantillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantillaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CuerpoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variables")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantillaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("PlantillaCorreo", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.PuntoLote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoteId"));

                    b.Property<int>("ContratacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("PuntosDisponibles")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PuntosOriginales")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LoteId");

                    b.HasIndex("EmpresaId", "FechaVencimiento");

                    b.ToTable("PuntoLote", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.PuntoMovimiento", b =>
                {
                    b.Property<long>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovimientoId"));

                    b.Property<int?>("CanjeId")
                        .HasColumnType("int");

                    b.Property<int?>("ContratacionId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaAsociadaEmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimientoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("LoteId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Puntos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("MovimientoId");

                    b.HasIndex("ContratacionId");

                    b.HasIndex("EmpresaAsociadaEmpresaId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "Estado", "FechaVencimiento");

                    b.ToTable("PuntoMovimiento", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Sectorista", b =>
                {
                    b.Property<int>("SectoristaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectoristaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectoristaId");

                    b.ToTable("Sectorista", (string)null);
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Canje", b =>
                {
                    b.HasOne("GestionBeneficios.Domain.Entities.Beneficio", "Beneficio")
                        .WithMany()
                        .HasForeignKey("BeneficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionBeneficios.Domain.Entities.EmpresaAsociada", "Empresa")
                        .WithMany("Canjes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficio");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.CargaMasivaDetalle", b =>
                {
                    b.HasOne("GestionBeneficios.Domain.Entities.CargaMasiva", null)
                        .WithMany("Detalles")
                        .HasForeignKey("CargaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Contratacion", b =>
                {
                    b.HasOne("GestionBeneficios.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Contrataciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionBeneficios.Domain.Entities.EmpresaAsociada", "Empresa")
                        .WithMany("Contrataciones")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionBeneficios.Domain.Entities.Sectorista", "Sectorista")
                        .WithMany()
                        .HasForeignKey("SectoristaId");

                    b.Navigation("Alumno");

                    b.Navigation("Empresa");

                    b.Navigation("Sectorista");
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.PuntoMovimiento", b =>
                {
                    b.HasOne("GestionBeneficios.Domain.Entities.Contratacion", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("ContratacionId");

                    b.HasOne("GestionBeneficios.Domain.Entities.EmpresaAsociada", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("EmpresaAsociadaEmpresaId");
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("Contrataciones");
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.CargaMasiva", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.Contratacion", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("GestionBeneficios.Domain.Entities.EmpresaAsociada", b =>
                {
                    b.Navigation("Canjes");

                    b.Navigation("Contrataciones");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
